model_name=Moirai

python -u run.py \
  --task_name Exp_TimeMoe \
  --is_training 0 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_5000_96 \
  --model $model_name \
  --data custom \
  --features M \
  --pretrained_path ../MOIRAI-small \
  --batch_size 32 \
  --patch_size 128 \
  --seq_len 5000  \
  --label_len 0 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMoe \
  --is_training 0 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_5000_192 \
  --model $model_name \
  --data custom \
  --features M \
  --pretrained_path ../MOIRAI-small \
  --batch_size 32 \
  --patch_size 128 \
  --seq_len 5000  \
  --label_len 0 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMoe \
  --is_training 0 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_5000_96 \
  --model $model_name \
  --data custom \
  --features M \
  --pretrained_path ../MOIRAI-base \
  --batch_size 32 \
  --patch_size 128 \
  --seq_len 5000  \
  --label_len 0 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMoe \
  --is_training 0 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_5000_192 \
  --model $model_name \
  --data custom \
  --features M \
  --pretrained_path ../MOIRAI-base \
  --batch_size 32 \
  --patch_size 128 \
  --seq_len 5000  \
  --label_len 0 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMoe \
  --is_training 0 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_5000_96 \
  --model $model_name \
  --data custom \
  --features M \
  --pretrained_path ../MOIRAI-large \
  --batch_size 32 \
  --patch_size 128 \
  --seq_len 5000  \
  --label_len 0 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMoe \
  --is_training 0 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_5000_192 \
  --model $model_name \
  --data custom \
  --features M \
  --pretrained_path ../MOIRAI-large \
  --batch_size 32 \
  --patch_size 128 \
  --seq_len 5000  \
  --label_len 0 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1